version: '3.8'

services:
  identity:
    image: quay.io/keycloak/keycloak:22.0.1
    command: start-dev --import-realm
    ports:
      - "8180:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin-secret
      KC_HOSTNAME: localhost
      KC_HEALTH_ENABLED: "true"
      KC_METRICS_ENABLED: "true"
      KEYCLOAK_LOGLEVEL: INFO
